# syntax=docker/dockerfile:1.15
ARG PHP_VERSION_ARG
ARG NODE_VERSION_ARG
ARG COMPOSER_VERSION_ARG
ARG FRANKENPHP_VERSION_ARG

FROM composer:${COMPOSER_VERSION_ARG:-2.8.4} AS composer
FROM node:${NODE_VERSION_ARG:-20} AS node
FROM dunglas/frankenphp:${FRANKENPHP_VERSION_ARG:-1.6.0}-php${PHP_VERSION_ARG:-8.4.7}-bookworm AS upstream

FROM upstream AS build

ARG PHP_EXT_REDIS_VERSION_ARG
ARG PHP_EXT_APCU_VERSION_ARG
ARG PHP_EXT_XDEBUG_VERSION_ARG

# include(_build.m4)

FROM upstream AS common

# include(_labels.m4)
# include(_common.m4)

FROM common AS prd

# include(_prd.m4)

FROM prd AS dev

# include(_dev.m4)