name: Docker Build images

run-name: Docker Build ${{ github.ref_name }} by @${{ github.actor }}

concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.ref }}

on:

  pull_request:
    branches:
      - main
    paths-ignore:
      - "docs/**"

  push:
    branches:
      - main
    tags:
      - '[0-9]+.[0-9]+.[0-9]+*'

  workflow_dispatch:
    inputs:
      version:
        description: "Docker Image Version"
        required: false
        type: string

jobs:

  prepare:

    runs-on: ubuntu-24.04

    outputs:
#      # Push if it's a scheduled job, a tag, or if we're committing to the main branch
#      push: ${{ (github.event_name == 'schedule' || (github.event_name == 'workflow_dispatch' && inputs.version) || startsWith(github.ref, 'refs/tags/') || (github.ref == 'refs/heads/main' && github.event_name != 'pull_request')) && true || false }}
#      variants: ${{ steps.matrix.outputs.variants }}
#      platforms: ${{ steps.matrix.outputs.platforms }}
#      metadata: ${{ steps.matrix.outputs.metadata }}
#      php_version: ${{ steps.check.outputs.php_version }}
#      php82_version: ${{ steps.check.outputs.php82_version }}
#      php83_version: ${{ steps.check.outputs.php83_version }}
#      skip: ${{ steps.check.outputs.skip }}
      ref: ${{ steps.check.outputs.ref || (github.event_name == 'workflow_dispatch' && inputs.version) || '' }}

    steps:

      - name: Checkout source
        uses: actions/checkout@v4

  docker-bake:

    runs-on: ubuntu-24.04

    needs:
      - prepare

    permissions:
      contents: read
      packages: write
      id-token: write

    steps:

      - name: Checkout source
        uses: actions/checkout@v4
  
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
  
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
  
      - name: Bake and push image
        uses: docker/bake-action@v6
        with:
          targets: prd,dev
          push: true
          files: |
            docker-bake.hcl
          set: |
            *.cache-from=type=gha
            *.cache-to=type=gha,mode=max
        env:
          GIT_HASH: ${{ github.sha }}
          DOCKER_IMAGE_VERSION: ${{ (github.ref_type == 'tag' && github.ref_name) || needs.prepare.outputs.ref || 'snapshot' }}
